apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtos-monitor
  namespace: monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rtos-monitor
  template:
    metadata:
      labels:
        app: rtos-monitor
    spec:
      containers:
        - name: rtos-monitor
          image: victorsandru/qnx-monitor-smart-city:latest
          imagePullPolicy: Always